<a href="https://colab.research.google.com/github/vanditasharma777/CASE_STUDY_ON_DIFFERENT_CLASSIFICATION_ALGORITHMS/blob/master/Machine_Learning_object_classification_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# importing Libraries
import sklearn
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
from tensorflow.keras.datasets import mnist
from tensorflow.keras.datasets import cifar10
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
import keras.backend as k

Using TensorFlow backend.


In [ ]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()
print('x_train shape:', x_train.shape)
print(x_train.shape[0], 'train samples')
print(x_test.shape[0], 'test samples')

x_train shape: (60000, 28, 28)
60000 train samples
10000 test samples


In [ ]:
x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train = x_train / 255.0
x_test = x_test / 255.0

In [ ]:
x_train = x_train.flatten().reshape(x_train.shape[0], x_train.shape[1]*x_train.shape[2])
x_test = x_test.flatten().reshape(x_test.shape[0],x_test.shape[1]*x_test.shape[2])

In [ ]:
#Using KNN for image classification
knn = KNeighborsClassifier(n_neighbors=7, metric='euclidean',n_jobs=-1)
knn.fit(x_train, y_train.ravel())
# Testing with KNN
y_pred_knn = knn.predict(x_test)
# confusion matrix 
print("Confusion matrix:")
print(confusion_matrix(y_test.ravel(),y_pred_knn))
# Classification report
print("Classification report:")
print(classification_report(y_test.ravel(),y_pred_knn))
#accuracy score 
print("Accuracy Score:")
print("Accuracy: ")
print(accuracy_score(y_pred_knn, y_test.ravel()))

Confusion matrix:
[[ 974    1    1    0    0    1    2    1    0    0]
 [   0 1133    2    0    0    0    0    0    0    0]
 [  11    8  988    2    1    0    2   16    4    0]
 [   0    3    2  976    1   12    1    7    4    4]
 [   1    8    0    0  945    0    5    1    1   21]
 [   5    0    0    8    2  866    4    1    2    4]
 [   6    3    0    0    3    2  944    0    0    0]
 [   0   25    3    0    1    0    0  989    0   10]
 [   6    4    6   11    7   12    1    6  916    5]
 [   5    6    3    6    8    4    1   11    2  963]]
Classification report:
              precision    recall  f1-score   support

           0       0.97      0.99      0.98       980
           1       0.95      1.00      0.97      1135
           2       0.98      0.96      0.97      1032
           3       0.97      0.97      0.97      1010
           4       0.98      0.96      0.97       982
           5       0.97      0.97      0.97       892
           6       0.98      0.99      0.98      

In [ ]:
# using svm for image classification
svclassifier = SVC(kernel='rbf')
print("Train model")
svclassifier.fit(x_train, y_train.ravel())
print("Compute predictions")
#predicting on test set
y_pred = svclassifier.predict(x_test)
# confusion matrix 
print("Confusion matrix:")
print(confusion_matrix(y_pred,y_test.ravel()))
# Classification report
print("Classification report:")
print(classification_report(y_pred,y_test.ravel()))
#accuracy score 
print("Accuracy Score:")
print(accuracy_score(y_pred, y_test.ravel()))

Train model
Compute predictions
Confusion matrix:
[[ 973    0    6    0    0    2    6    0    3    3]
 [   0 1126    1    0    0    0    2    6    0    4]
 [   1    3 1006    2    5    0    0   11    2    1]
 [   0    1    2  995    0    9    0    1    6    7]
 [   0    0    1    0  961    0    2    1    3   10]
 [   2    1    0    2    0  871    3    0    2    2]
 [   1    1    2    0    3    4  944    0    2    1]
 [   1    1    7    5    0    1    0  996    3    7]
 [   2    2    6    5    2    4    1    2  950    4]
 [   0    0    1    1   11    1    0   11    3  970]]
Classification report:
              precision    recall  f1-score   support

           0       0.99      0.98      0.99       993
           1       0.99      0.99      0.99      1139
           2       0.97      0.98      0.98      1031
           3       0.99      0.97      0.98      1021
           4       0.98      0.98      0.98       978
           5       0.98      0.99      0.98       883
           6     

In [ ]:
# Using Naive Bayes for image classification
model = GaussianNB()
df# Train the model using the training sets
print("Train model")
model.fit(x_train,y_train.ravel())
#Predict Output
print("Compute predictions")
predicted= model.predict(x_test)
# classification report
print("Classification Report")
print(classification_report(predicted,y_test.ravel()))
# confusion matrix
print("Confusion Matrix")
print(confusion_matrix(predicted,y_test.ravel()))
# accuracy score
print("Accuracy Score")
print(accuracy_score(predicted,y_test.ravel()))

Train model
Compute predictions
Classification Report
              precision    recall  f1-score   support

           0       0.89      0.79      0.84      1101
           1       0.95      0.85      0.90      1276
           2       0.26      0.90      0.40       294
           3       0.35      0.71      0.47       498
           4       0.17      0.88      0.29       190
           5       0.05      0.55      0.09        80
           6       0.93      0.65      0.77      1377
           7       0.27      0.88      0.42       319
           8       0.67      0.28      0.40      2280
           9       0.95      0.37      0.53      2585

    accuracy                           0.56     10000
   macro avg       0.55      0.69      0.51     10000
weighted avg       0.78      0.56      0.59     10000

Confusion Matrix
[[ 870    0   79   32   19   71   12    0   13    5]
 [   0 1079   25   39    2   25   12   15   72    7]
 [   3    2  266    6    5    1    3    2    3    3]
 [   5    1

In [ ]:
# using Decision tree classifier for image classification
dtf = DecisionTreeClassifier()
print("Train model")
dtf.fit(x_train, y_train.ravel())
print("Compute predictions")
predicted1 = dtf.predict(x_test)
#Evaluation
print("Confusion matrix")
print(confusion_matrix(predicted1,y_test.ravel()))
print("Classification report")
print(classification_report(predicted1,y_test.ravel()))
print("Accuracy: ")
print(accuracy_score(predicted1, y_test.ravel()))

Train model
Compute predictions
Confusion matrix
[[ 918    2   13    8    4   13   17    2   15   14]
 [   0 1092    8    3    2    9    4   12    5    4]
 [   6   12  884   31    9    5   12   27   29    8]
 [   6    2   33  863    4   45    7   15   33   25]
 [   6    2   17    7  866    9   19    9   23   40]
 [  11    3   15   45    7  742   25    4   21   12]
 [  13    6    8    7   13   20  845    1   18    8]
 [   2    5   22   10   10    6    1  925    8   19]
 [   9   10   25   22   21   24   26    8  798   22]
 [   9    1    7   14   46   19    2   25   24  857]]
Classification report
              precision    recall  f1-score   support

           0       0.94      0.91      0.92      1006
           1       0.96      0.96      0.96      1139
           2       0.86      0.86      0.86      1023
           3       0.85      0.84      0.84      1033
           4       0.88      0.87      0.87       998
           5       0.83      0.84      0.84       885
           6       

In [ ]:
# Using Random forest classifier for image classification
clf = RandomForestClassifier()
print("Train model")
clf.fit(x_train, y_train.ravel())
print("Compute predictions")
predicted = clf.predict(x_test)
#Evaluation
print("Confusion matrix")
print(confusion_matrix(predicted,y_test.ravel()))
print("Classification report")
print(classification_report(predicted,y_test.ravel()))
print("Accuracy: ")
print(accuracy_score(predicted, y_test.ravel()))

Train model
Compute predictions
Confusion matrix
[[ 972    0    5    0    1    2    7    1    3    6]
 [   0 1123    0    0    0    0    3    2    0    5]
 [   0    1  999    9    1    1    0   19    6    2]
 [   0    4    6  974    0   14    0    0    7    8]
 [   0    0    3    0  959    4    3    1    4   14]
 [   2    2    1    4    0  858    4    0    5    2]
 [   2    3    4    0    5    5  939    0    4    1]
 [   1    0    9    9    0    2    0  992    4    6]
 [   2    1    5   10    2    5    2    3  933    7]
 [   1    1    0    4   14    1    0   10    8  958]]
Classification report
              precision    recall  f1-score   support

           0       0.99      0.97      0.98       997
           1       0.99      0.99      0.99      1133
           2       0.97      0.96      0.97      1038
           3       0.96      0.96      0.96      1013
           4       0.98      0.97      0.97       988
           5       0.96      0.98      0.97       878
           6       

**CNN FOR MNIST DIGIT DATASET CLASSIFICATION**

In [ ]:
import keras.backend as k
img_rows,img_cols = 28,28
#print the new label
if k.image_data_format() == 'channels_first':
    x_train = x_train.reshape(x_train.shape[0], 1, img_rows, img_cols)
    x_test = x_test.reshape(x_test.shape[0], 1, img_rows, img_cols)
    input_shape = (1, img_rows, img_cols)
else:
    x_train = x_train.reshape(x_train.shape[0], img_rows, img_cols, 1)
    x_test = x_test.reshape(x_test.shape[0], img_rows, img_cols, 1)
    input_shape = (img_rows, img_cols, 1)

x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train /= 255
x_test /= 255
print('x_train shape:', x_train.shape)
print(x_train.shape[0], 'train samples')
print(x_test.shape[0], 'test samples')

x_train shape: (60000, 28, 28, 1)
60000 train samples
10000 test samples


In [ ]:
from keras.utils import np_utils
# one-hot encode the labels
y_train = np_utils.to_categorical(y_train, 10)
y_test = np_utils.to_categorical(y_test, 10)

In [ ]:
y_test.shape,y_train.shape

((10000, 10), (60000, 10))

In [ ]:
from keras.applications.vgg16 import VGG16
from keras.layers import Flatten,Dense,Dropout,Softmax,Conv2D, MaxPooling2D
from keras.models import Sequential
from keras.optimizers import Adam
from keras.datasets import cifar10 


In [ ]:
# Build the CNN model
import keras
num_classes=10
batch_size=128
epochs=12
model = keras.models.Sequential()
model = Sequential()
model.add(Conv2D(32, kernel_size=(3, 3),activation='relu',input_shape=input_shape))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(num_classes, activation='softmax'))
model.compile(loss=keras.losses.categorical_crossentropy,optimizer=keras.optimizers.Adadelta(),metrics=['accuracy'])
model.fit(x_train, y_train, batch_size=batch_size,epochs=epochs,verbose=1,validation_data=(x_test, y_test))                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
           

Train on 60000 samples, validate on 10000 samples
Epoch 1/12
60000/60000 [==============================] - 143s 2ms/step - loss: 0.2718 - accuracy: 0.9169 - val_loss: 0.0577 - val_accuracy: 0.9819
Epoch 2/12
60000/60000 [==============================] - 142s 2ms/step - loss: 0.0900 - accuracy: 0.9728 - val_loss: 0.0405 - val_accuracy: 0.9863
Epoch 3/12
60000/60000 [==============================] - 142s 2ms/step - loss: 0.0681 - accuracy: 0.9797 - val_loss: 0.0337 - val_accuracy: 0.9882
Epoch 4/12
60000/60000 [==============================] - 142s 2ms/step - loss: 0.0557 - accuracy: 0.9831 - val_loss: 0.0328 - val_accuracy: 0.9888
Epoch 5/12
60000/60000 [==============================] - 142s 2ms/step - loss: 0.0465 - accuracy: 0.9862 - val_loss: 0.0274 - val_accuracy: 0.9912
Epoch 6/12
60000/60000 [==============================] - 142s 2ms/step - loss: 0.0430 - accuracy: 0.9870 - val_loss: 0.0284 - val_accuracy: 0.9906
Epoch 7/12
60000/60000 [==============================] - 142s

In [ ]:
score = model.evaluate(x_test, y_test, verbose=0)                                              
print('Test loss:', score[0])
print('Test accuracy:', score[1])    

Test loss: 0.026354128892004745
Test accuracy: 0.9926000237464905


In [ ]:
test_predictions = model.predict_classes(x_test, batch_size=128, verbose=0) 
import numpy as np
rounded_labels=np.argmax(y_test, axis=1)
rounded_labels[1]
print("confusion matrix")
cm = confusion_matrix(rounded_labels, test_predictions)
print(cm)
print("classification report:")
print(classification_report(rounded_labels, test_predictions, target_names= None))
print("Accuracy score:")
print(accuracy_score(rounded_labels,test_predictions))

confusion matrix
[[ 978    0    0    0    0    0    0    1    1    0]
 [   0 1134    1    0    0    0    0    0    0    0]
 [   1    1 1024    0    1    0    1    4    0    0]
 [   0    0    2 1005    0    2    0    0    1    0]
 [   0    0    0    0  978    0    1    0    0    3]
 [   2    0    0    7    0  881    2    0    0    0]
 [   5    3    0    0    1    1  947    0    1    0]
 [   0    3    5    0    0    0    0 1016    1    3]
 [   4    0    1    1    0    0    0    0  966    2]
 [   0    1    0    1    4    3    0    1    2  997]]
classification report:
              precision    recall  f1-score   support

           0       0.99      1.00      0.99       980
           1       0.99      1.00      1.00      1135
           2       0.99      0.99      0.99      1032
           3       0.99      1.00      0.99      1010
           4       0.99      1.00      0.99       982
           5       0.99      0.99      0.99       892
           6       1.00      0.99      0.99       

# **FOR CIFAR10 DATASET**

In [1]:
import pandas as pd
from tensorflow.keras.datasets import cifar10
from sklearn.metrics import classification_report, confusion_matrix,accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [2]:
#provide dataset
(X_train, Y_train), (X_test, Y_test) = cifar10.load_data()
print('x_train shape:', X_train.shape)
print(X_train.shape[0], 'train samples')
print(X_test.shape[0], 'test samples')


170500096/170498071 [==============================] - 6s 0us/step
x_train shape: (50000, 32, 32, 3)
50000 train samples
10000 test samples


In [ ]:
X_train = X_train.astype('float32')                                                                                                                    
X_test = X_test.astype('float32')
X_train = X_train / 255.0
X_test = X_test / 255.0

In [ ]:
X_train = X_train.flatten().reshape(X_train.shape[0], X_train.shape[1]*X_train.shape[2]*X_train.shape[3])
X_test = X_test.flatten().reshape(X_test.shape[0],X_test.shape[1]*X_test.shape[2]*X_test.shape[3])

In [ ]:
#Using KNN for image classification
knn = KNeighborsClassifier(n_neighbors=7, metric='euclidean',n_jobs=-1)
knn.fit(X_train, Y_train.ravel())
# Testing with KNN
y_pred_knn = knn.predict(X_test)
#accuracy score 
print(classification_report(Y_test.ravel(),y_pred_knn))

              precision    recall  f1-score   support

           0       0.40      0.52      0.45      1000
           1       0.70      0.20      0.30      1000
           2       0.22      0.44      0.29      1000
           3       0.28      0.20      0.23      1000
           4       0.23      0.52      0.32      1000
           5       0.40      0.20      0.27      1000
           6       0.35      0.27      0.30      1000
           7       0.70      0.20      0.31      1000
           8       0.39      0.69      0.50      1000
           9       0.73      0.14      0.23      1000

    accuracy                           0.34     10000
   macro avg       0.44      0.34      0.32     10000
weighted avg       0.44      0.34      0.32     10000



In [ ]:
# confusion matrix 
print(confusion_matrix(Y_test.ravel(),y_pred_knn))

[[518   7 118  12  46   5  30   5 255   4]
 [118 195 124  51 173  32  55   8 223  21]
 [110   2 437  50 250  24  65   7  53   2]
 [ 66   5 243 199 214 102 108  11  51   1]
 [ 60   0 268  33 521  14  44  11  48   1]
 [ 63   2 225 156 201 204  80  10  53   6]
 [ 22   1 271  56 319  32 265   1  32   1]
 [ 78   8 185  57 294  60  48 196  68   6]
 [112  10  47  34  69  12  14   7 688   7]
 [152  50  95  59 135  19  52  25 278 135]]


In [ ]:
result2=accuracy_score(Y_test,y_pred_knn)
print("Accuracy:",result2)

Accuracy: 0.3358


In [ ]:
#Create a Gaussian Classifier
model = GaussianNB()

# Train the model using the training sets
model.fit(X_train,Y_train.ravel())

#Predict Output
predicted= model.predict(X_test)

print("classification report")
print(classification_report(predicted,Y_test.ravel()))

print("confusion matrix")
confusion_matrix(predicted,Y_test.ravel())


classification report
              precision    recall  f1-score   support

           0       0.49      0.27      0.35      1817
           1       0.17      0.41      0.24       405
           2       0.08      0.19      0.12       443
           3       0.08      0.25      0.12       305
           4       0.42      0.24      0.30      1737
           5       0.26      0.31      0.29       840
           6       0.47      0.25      0.33      1846
           7       0.13      0.42      0.20       310
           8       0.47      0.39      0.42      1219
           9       0.41      0.38      0.39      1078

    accuracy                           0.30     10000
   macro avg       0.30      0.31      0.28     10000
weighted avg       0.39      0.30      0.32     10000

confusion matrix


array([[494, 141, 225, 163,  86, 156, 106, 134, 168, 144],
       [ 20, 166,  24,  36,   8,  17,   2,  24,  41,  67],
       [ 39,  24,  83,  54,  57,  55,  60,  36,  18,  17],
       [ 10,  31,  15,  76,  26,  51,  18,  41,  17,  20],
       [ 84,  66, 292, 151, 417, 167, 228, 228,  56,  48],
       [ 34,  72,  48, 129,  38, 264,  46,  94,  83,  32],
       [ 50, 192, 209, 262, 265, 159, 467, 102,  39, 101],
       [  9,  19,  21,  26,  22,  36,  15, 131,   8,  23],
       [200, 121,  54,  34,  50,  57,  19,  72, 471, 141],
       [ 60, 168,  29,  69,  31,  38,  39, 138,  99, 407]])

In [ ]:
print("Accuracy: ")
print(accuracy_score(predicted, Y_test.ravel()))

Accuracy: 
0.2976


In [ ]:
rtc = RandomForestClassifier()
print("Train model")
rtc.fit(X_train, Y_train.ravel())
print("Compute predictions")
r_pred = rtc.predict(X_test)
#Evaluation
print("Confusion matrix")
print(confusion_matrix(r_pred,Y_test.ravel()))
print("Classification report")
print(classification_report(r_pred,Y_test.ravel()))

Train model
Compute predictions
Confusion matrix
[[565  35 102  49  55  37   7  52  91  50]
 [ 46 540  45  48  22  33  41  54  85 159]
 [ 57  15 336  81 146  82  78  48  17  18]
 [ 20  41  78 281  53 150  66  49  33  28]
 [ 39  20 153  75 391  73 106 102  21  18]
 [ 14  27  62 184  45 385  61  79  28  22]
 [ 15  41 113 131 148  93 566  50  12  21]
 [ 22  35  58  57  94  90  26 459  19  38]
 [159  66  24  29  24  23   8  26 615  74]
 [ 63 180  29  65  22  34  41  81  79 572]]
Classification report
              precision    recall  f1-score   support

           0       0.56      0.54      0.55      1043
           1       0.54      0.50      0.52      1073
           2       0.34      0.38      0.36       878
           3       0.28      0.35      0.31       799
           4       0.39      0.39      0.39       998
           5       0.39      0.42      0.40       907
           6       0.57      0.48      0.52      1190
           7       0.46      0.51      0.48       898
           

In [ ]:
print("Accuracy: ")
print(accuracy_score(r_pred, Y_test.ravel()))

Accuracy: 
0.471


In [ ]:
dtf1 = DecisionTreeClassifier()
print("Train model")
dtf1.fit(X_train, Y_train.ravel())
print("Compute predictions")
predicted2 = dtf1.predict(X_test)
#Evaluation
print("Confusion matrix")
print(confusion_matrix(predicted2,Y_test.ravel()))
print("Classification report")
print(classification_report(predicted2,Y_test.ravel()))
print("Accuracy: ")
print(accuracy_score(predicted2, Y_test.ravel()))

Train model
Compute predictions
Confusion matrix
[[343  74 101  68  65  44  48  76 138  97]
 [ 80 263  46  48  47  56  52  74 102 161]
 [ 81  63 200 116 150 105 113  88  48  45]
 [ 48  84 101 188  78 160 130  93  54  76]
 [ 50  60 148 106 235  89 150  94  50  45]
 [ 56  52 113 141 107 232  92 106  43  61]
 [ 42  45 109 125 118  95 275  62  26  51]
 [ 72  70  87  97 108  98  61 277  40  84]
 [147 122  41  58  41  62  26  58 391 101]
 [ 81 167  54  53  51  59  53  72 108 279]]
Classification report
              precision    recall  f1-score   support

           0       0.34      0.33      0.33      1054
           1       0.26      0.28      0.27       929
           2       0.20      0.20      0.20      1009
           3       0.19      0.19      0.19      1012
           4       0.23      0.23      0.23      1027
           5       0.23      0.23      0.23      1003
           6       0.28      0.29      0.28       948
           7       0.28      0.28      0.28       994
           

In [3]:
#Taking subset of data 20000 samples out of 50000 for training
X_train = X_train[20000:40000,:,:,:]
print(X_train.shape)

#Taking 5000 samples out of 10000 for testing
X_test = X_test[5000:10000,:,:,:]
print(X_test.shape)

#Taking sample from Target label dataset
Y_train = Y_train[20000:40000,:]
Y_test = Y_test[5000:10000,:]

(20000, 32, 32, 3)
(5000, 32, 32, 3)


In [4]:
# Normalizing the data
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')
X_train = X_train / 255.0
X_test = X_test / 255.0

In [5]:
X_train = X_train.flatten().reshape(X_train.shape[0], X_train.shape[1]*X_train.shape[2]*X_train.shape[3])
X_test = X_test.flatten().reshape(X_test.shape[0],X_test.shape[1]*X_test.shape[2]*X_test.shape[3])

In [6]:
# using svm for image classification
svclassifier = SVC(kernel='rbf')
print("Train model")
svclassifier.fit(X_train, Y_train.ravel())
print("Compute predictions")
#predicting on test set
y_pred = svclassifier.predict(X_test)
# confusion matrix 
print("Confusion matrix:")
print(confusion_matrix(y_pred,Y_test.ravel()))
# Classification report
print("Classification report:")
print(classification_report(y_pred,Y_test.ravel()))
#accuracy score  
print("Accuracy Score:")
print(accuracy_score(y_pred, Y_test.ravel()))

Train model
Compute predictions
Confusion matrix:
[[290  14  43  16  25  12   3  18  43  24]
 [ 10 285  14  20   6  12  10  14  38  76]
 [ 29  10 182  48  67  51  58  22  13   6]
 [ 11  24  43 171  31 102  41  49  18  26]
 [  8  10  67  37 204  32  51  52   9   5]
 [ 11   9  38  81  29 201  29  39  14  13]
 [ 12  10  56  70  75  44 289  28   7  10]
 [ 12  16  20  16  38  36  13 243  11  18]
 [ 95  30  15  20  10  15   7   5 312  26]
 [ 34  87  10  24   8   7   8  35  31 283]]
Classification report:
              precision    recall  f1-score   support

           0       0.57      0.59      0.58       488
           1       0.58      0.59      0.58       485
           2       0.37      0.37      0.37       486
           3       0.34      0.33      0.34       516
           4       0.41      0.43      0.42       475
           5       0.39      0.43      0.41       464
           6       0.57      0.48      0.52       601
           7       0.48      0.57      0.52       423
         

In [ ]:
import keras
import tensorflow
from keras.datasets import cifar10 
from keras.models import Sequential 
from keras.layers import Dense, Dropout, Flatten 
from keras.layers import Conv2D, MaxPooling2D
from keras import backend as k
import keras.utils 
import sklearn
from sklearn.metrics import classification_report,confusion_matrix
batch_size = 128
num_classes = 10
#epochs = 20


In [ ]:
# input image dimensions
img_rows, img_cols = 32, 32

# the data, split between train and test sets
(x_train, y_train), (x_test, y_test) = cifar10.load_data()

In [ ]:
# print the new label
if k.image_data_format() == 'channels_first':
    x_train = x_train.reshape(x_train.shape[0], 3, img_rows, img_cols)
    x_test = x_test.reshape(x_test.shape[0], 3, img_rows, img_cols)
    input_shape = (3, img_rows, img_cols)
else:
    x_train = x_train.reshape(x_train.shape[0], img_rows, img_cols, 3)
    x_test = x_test.reshape(x_test.shape[0], img_rows, img_cols, 3)
    input_shape = (img_rows, img_cols, 3)

x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train /= 255
x_test /= 255
print('x_train shape:', x_train.shape)
print(x_train.shape[0], 'train samples')
print(x_test.shape[0], 'test samples')

x_train shape: (50000, 32, 32, 3)
50000 train samples
10000 test samples


In [ ]:
# convert class vectors to binary class matrices
y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)


In [ ]:
# Build the CNN model
model = keras.models.Sequential()
model = Sequential()
model.add(Conv2D(32, kernel_size=(5, 5),activation='relu',input_shape=input_shape))
model.add(Conv2D(64, (5, 5), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(num_classes, activation='softmax'))
model.compile(loss=keras.losses.categorical_crossentropy,
              optimizer=keras.optimizers.Adadelta(),
              metrics=['accuracy'])
model.fit(x_train, y_train, batch_size=batch_size,epochs=epochs,verbose=1,
          validation_data=(x_test, y_test))
score = model.evaluate(x_test, y_test, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])

Train on 50000 samples, validate on 10000 samples
Epoch 1/20
50000/50000 [==============================] - 14s 286us/step - loss: 1.8296 - accuracy: 0.3366 - val_loss: 1.4332 - val_accuracy: 0.4928
Epoch 2/20
50000/50000 [==============================] - 8s 161us/step - loss: 1.4136 - accuracy: 0.5009 - val_loss: 1.2068 - val_accuracy: 0.5724
Epoch 3/20
50000/50000 [==============================] - 8s 162us/step - loss: 1.2247 - accuracy: 0.5713 - val_loss: 1.1258 - val_accuracy: 0.6019
Epoch 4/20
50000/50000 [==============================] - 8s 161us/step - loss: 1.1206 - accuracy: 0.6111 - val_loss: 1.0437 - val_accuracy: 0.6326
Epoch 5/20
50000/50000 [==============================] - 8s 161us/step - loss: 1.0373 - accuracy: 0.6366 - val_loss: 0.9446 - val_accuracy: 0.6695
Epoch 6/20
50000/50000 [==============================] - 8s 161us/step - loss: 0.9720 - accuracy: 0.6619 - val_loss: 1.0078 - val_accuracy: 0.6488
Epoch 7/20
50000/50000 [==============================] - 8s 